server:
  port: 8080

spring:
  application:
    name: hollowtone-shop

  datasource:
    url: jdbc:mysql://localhost:3306/hollowtone?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/oauth2/callback/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com

# Eigene (custom) Konfiguration für unsere JWTs
security:
  jwt:
    issuer: "hollowtone"
    access-token-ttl-minutes: 30
    refresh-token-ttl-days: 30
    # In DEV liegen die Schlüssel als Ressourcen-Dateien (nicht für Prod)
    private-key-path: "keys/jwt_ec_private.pem"
    public-key-path: "keys/jwt_ec_public.pem"

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.security: info
